//This module is used to add color to the console output, making it easier to read debug and log messages.
require('colors');
//This imports the EventEmitter class from Node.js, which allows the GptService class to emit
// and listen for events.
const EventEmitter = require('events');
//This imports the OpenAI class, which will be used to interact with the OpenAI API.
const OpenAI = require('openai');

class GptService extends EventEmitter {

  //This is the constructor method for the GptService class, which initializes an instance of the class.
  constructor(businessDescription) {
    super();

    //Create an instance of the OpenAI class and assign it to the openai property of the GptService instance.
    this.openai = new OpenAI();

    //Initializes the userContext property, which is an array containing a single object.
    //This object defines the role and initial context for the conversation with the OpenAI API.
    //The context specifies that appointment bookings are not provided and includes the provided businessDescription.
    //This is important for setting the initial behavior and scope of the AI's responses.
    this.userContext = [
      { 'role': 'system', 'content': `${businessDescription}` }
    ];

    this.partialResponseIndex = 0;
  }

  // Add the callSid to the chat context in case
  // ChatGPT decides to transfer the call.
  setCallSid(callSid) {
    //This line adds a new object to the userContext array. The object has two properties:
    //'role': 'system': This specifies that the role of this message is system,
    //indicating that it is a system-level message and not from a user or assistant.
    //'content': callSid: ${callSid}``: This sets the content of the message to include the callSid.
    //By embedding the callSid in the context, it ensures that this identifier is included
    //in the context for subsequent interactions with the OpenAI API, which
    //is useful for tracking the conversation or for any logic dependent on the callSid.
    this.userContext.push({ 'role': 'system', 'content': `callSid: ${callSid}` });
  }

  //async: Indicates that this method is asynchronous and will use the await keyword to wait for promises.
  //text: The input text to be processed by the AI.
  //interactionCount: A counter to keep track of the number of interactions.
  //role: The role of the message sender, defaulting to 'user'.
  //name: The name of the message sender, defaulting to 'user'.
  async completion(text, interactionCount, role = 'user', name = 'user') {

    //Add the input text to the userContext with the appropriate role and name.
    if (name != 'user') {
      this.userContext.push({ 'role': role, 'name': name, 'content': text });
    } else {
      this.userContext.push({ 'role': role, 'content': text });
    }

    //Initiate a request to the OpenAI API to generate a response.
    const stream = await this.openai.chat.completions.create({
      model: 'gpt-4-turbo', //Specifies the model to be used for generating the response.
      messages: this.userContext, //Provide the context for the conversation
      stream: true, //Indicate that the response should be streamed.
    });

    let completeResponse = '';
    let partialResponse = '';

    //Iterate over the streamed response chunks from the OpenAI API
    for await (const chunk of stream) {
      let content = chunk.choices[0]?.delta?.content || '';
      let finishReason = chunk.choices[0].finish_reason;

      completeResponse += content;
      partialResponse += content;

      //Check if the content ends with a sentence terminator (., ?, !) or if the response is marked as finished.
      if (content.trim().slice(-1) === '.' || content.trim().slice(-1) === '?' || content.trim().slice(-1) === '!' || finishReason === 'stop') {

        //Split the partialResponse into sentences.
        let sentences = partialResponse.split('.');

        //For each sentence, if it's not empty, create a gptReply object and emit a gptreply event
        //with the gptReply and interactionCount.
        sentences.forEach((sentence) => {
          if (sentence.trim() !== '') {
            const gptReply = {
              partialResponseIndex: this.partialResponseIndex,
              partialResponse: sentence.trim()
            };

            this.emit('gptreply', gptReply, interactionCount);
            this.partialResponseIndex++;
          }
        });
        partialResponse = '';
      }
    }

    //This method adds a new element to the end of the userContext array.
    //role: Set to 'assistant', indicating that the response is from the AI assistant.
    //content: Set to completeResponse, which is the full response generated by the OpenAI API.
    this.userContext.push({'role': 'assistant', 'content': completeResponse});
    console.log(`GPT -> user context length: ${this.userContext.length}`.green);
  }
}

module.exports = { GptService };